import '@material/web/dialog/dialog.js';
import '@material/web/tabs/tabs.js';
import '@material/web/button/filled-button.js';
import '@material/web/checkbox/checkbox.js';
import '@material/web/select/outlined-select.js';
import '@material/web/iconbutton/icon-button.js';
import '@material/web/select/filled-select.js';
import '@material/web/switch/switch.js';
import '@material/web/textfield/filled-text-field.js';
